name: uas_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.0
  firebase_auth_web: ^5.2.0
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.7
  flutter:
    sdk: flutter
  get: 4.6.5
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
